In [2]:
import numpy as np
import pandas as pd 
import seaborn as sns 

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [3]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv')

### SO what we have done here is humne fir se saare encoded numerical columns ko categorical column mein convert kar liya hai and now we want ki yeh saare kaam sklearn ki jo PIPELINE hum banayge usme internally ho jaaye

In [4]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [5]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [6]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [7]:
df.sample(5)

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
792,flat,sector 89,0.42,2.0,2.0,2,Relatively New,769.0,0.0,0.0,unfurnished,Low,Mid Floor
1302,flat,sector 66,2.80,3.0,4.0,3,Relatively New,1700.0,1.0,0.0,semifurnished,Medium,Mid Floor
3545,house,sector 27,8.00,9.0,9.0,3,Relatively New,3042.0,1.0,1.0,furnished,Medium,Mid Floor
3274,flat,sector 71,0.55,2.0,2.0,1,Relatively New,600.0,0.0,0.0,semifurnished,Low,Mid Floor
1322,flat,sector 36,0.37,1.0,1.0,1,Relatively New,319.0,0.0,0.0,semifurnished,Medium,Mid Floor

In [8]:
# columns alag lag kar liye  
X = df.drop(columns=['price'])
y = df['price']

In [9]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

### Ordinal encoding

In [10]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

### now we are applying the transformer inside a scikit learn pipeline

In [11]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode)
    ], 
    remainder='passthrough'
)

### PIPELINE MEIN 2 STEPPS MEIN KAAM HOGA PEHELE WE WILL APPLY TRANFORMATION ACCORDING TO PREPROCESSOR  TO ALL THE COLUMNS AND AFTER TAHT JO DATA BACH JAYEGA USPE LINEAR REGRXN ALGO CHALA KE MODEL TRAIN KREGE AND ALSO AFTER THAT
### CORSSS VALIDATION BHI PERFORM KRE

In [12]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [13]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [14]:
scores.mean(),scores.std()

(np.float64(0.7363096633436828), np.float64(0.03238005754429936))

## SO WE COULD SEE ABOVE THAT ORDINAL ENCODING HAS NOT PERFORMED WELL WOTH LINEAR REGRXN

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [16]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [17]:
y_pred = pipeline.predict(X_test)

In [18]:
y_pred = np.expm1(y_pred)

In [19]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.9463822160089356

### MSE IS .94 THAT IS ON AN AVG HUMM 94 LAKHS KI GALTI KAR RHE HAI

## AND NOW WHAT WE HAVE DONE IS UPAR JO POORA FLOW BANAYA HAI USKO EK FUNCTIONMEIN CONVERT KAR DENGE AND WHAT IT'LL TAKE AS INPUT IS A Ml ALGO NAME

In [20]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [31]:
%pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (3.1.3)
Requirement already satisfied: numpy in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from xgboost) (2.3.1)
Requirement already satisfied: scipy in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from xgboost) (1.15.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor, AdaBoostRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor

In [35]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [36]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [37]:
model_output

[['linear_reg', np.float64(0.7363096633436828), 0.9463822160089356],
 ['svr', np.float64(0.7642012011196355), 0.8472636473483922],
 ['ridge', np.float64(0.7363125343993554), 0.9463387741853386],
 ['LASSO', np.float64(0.05943378064493573), 1.528905986892753],
 ['decision tree', np.float64(0.7714087911955497), 0.7516118014149412],
 ['random forest', np.float64(0.8813391461347699), 0.5313043879786475],
 ['extra trees', np.float64(0.8683804718770276), 0.5543738132608536],
 ['gradient boosting', np.float64(0.872523641033693), 0.5761564013726328],
 ['adaboost', np.float64(0.7578833489432648), 0.816914670780028],
 ['mlp', np.float64(0.79637460565206), 0.7299801066869289],
 ['xgboost', np.float64(0.8894876835260124), 0.5040475141482346]]

In [38]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [39]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.889488  0.504048
5       random forest  0.881339  0.531304
6         extra trees  0.868380  0.554374
7   gradient boosting  0.872524  0.576156
9                 mlp  0.796375  0.729980
4       decision tree  0.771409  0.751612
8            adaboost  0.757883  0.816915
1                 svr  0.764201  0.847264
2               ridge  0.736313  0.946339
0          linear_reg  0.736310  0.946382
3               LASSO  0.059434  1.528906

### One hot encoding

In [40]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first'),['sector','agePossession','furnishing_type'])
    ], 
    remainder='passthrough'
)

In [41]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [42]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [43]:
scores.mean()

np.float64(0.8546094810971422)

In [44]:
scores.std()

np.float64(0.015997422908695623)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [46]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first'),
                                                  ['sector', 'agePossession',
                                                   'furnishing_type'])])),
                ('regressor', LinearRegression())])

In [47]:
y_pred = pipeline.predict(X_test)

In [48]:
y_pred = np.expm1(y_pred)

In [49]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.6497514315131458

In [50]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [51]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [52]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages\sklearn\neural_network\_multilayer_perceptron.py:780: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [53]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [54]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.894403  0.471318
10            xgboost  0.895850  0.493456
5       random forest  0.889688  0.505653
9                 mlp  0.875194  0.553526
7   gradient boosting  0.876760  0.570189
0          linear_reg  0.854609  0.649751
2               ridge  0.854739  0.652915
4       decision tree  0.809488  0.697442
1                 svr  0.769741  0.834124
8            adaboost  0.747798  0.856097
3               LASSO  0.059434  1.528906

###  NOW WE HAVE INCREASED AMNY COLUMNS BECAUSE OF ONE HOT ENCODING AND NOW WE NEED TO REDUCE THE DIMENSIONALITY SO WE CAN DO PCA WITH ONE HOT ENCODING

### one Hot Encoding with PCA

In [55]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ], 
    remainder='passthrough'
)

In [56]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('pca', PCA(n_components=0.95)),
    ('regressor', LinearRegression())
])

In [57]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [58]:
scores.mean()

np.float64(0.06225201431451135)

In [59]:
scores.std()

np.float64(0.01986059407164016)

In [60]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [61]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [62]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [63]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [64]:
model_df.sort_values(['mae'])

                 name        r2       mae
5       random forest  0.763553  0.659027
6         extra trees  0.739929  0.696872
4       decision tree  0.696442  0.761509
10            xgboost  0.622205  0.967581
7   gradient boosting  0.610623  0.987906
8            adaboost  0.315471  1.344838
1                 svr  0.218073  1.361163
9                 mlp  0.211167  1.408112
2               ridge  0.062252  1.526707
0          linear_reg  0.062252  1.526707
3               LASSO  0.059676  1.528739

### NOW WE CAN SEE RESULTS ARE NOT AS GOOD AS WE ARE EXPECTING USING PCA SO AS FOR NOW WE ARE NOT CONSIDERING THIS

In [66]:
%pip install category_encoders

Defaulting to user installation because normal site-packages is not writeable
Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from category_encoders) (2.3.1)
Requirement already satisfied: pandas>=1.0.5 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from category_encoders) (2.3.2)
Requirement already satisfied: patsy>=0.5.1 in C:\ProgramData\anaconda3\Lib\site-packages (from category_encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from category_encoders) (1.7.0)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from category_encoders) (1.15.3)
Requirement already satisfied: statsmodels>=0.9.0 in C:\ProgramData\anaconda3\Lib\site-packages (from category_encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in C:\Users\UdsPC\AppData\Roaming\Python\Python313\site-packages (from statsmodels>=0.9.0->category_encoders) (25.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## TARGET ENCODING USED TO THOSE COLS WHICH HAVE GOT HIGH CARDINALITY OR DIMESIONALITY 

## SO WE NEED TO BE VERY CAREFUL WITH TARGET ENCODING AS HERE IS CHANCE OF DATA LEAKAGE SO ALWAYS DO TRAIN TEST SPLIT BEFORE THIS BUT IN THIS CASE WE ARE ANYWAYS DOING CROSS VALIDATION SO ITNA FARQ NHI PDEGA

### Target Encoder

In [69]:
import category_encoders as ce

columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [70]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [71]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [72]:
scores.mean(),scores.std()

(np.float64(0.8295219182255362), np.float64(0.018384463379122782))

In [73]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [74]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [75]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [76]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [77]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.904798  0.447518
5       random forest  0.901273  0.452535
6         extra trees  0.902266  0.456050
7   gradient boosting  0.889170  0.509250
4       decision tree  0.825384  0.567926
9                 mlp  0.850903  0.608847
8            adaboost  0.819520  0.667690
0          linear_reg  0.829522  0.713011
2               ridge  0.829536  0.713523
1                 svr  0.782917  0.818851
3               LASSO  0.059434  1.528906

### Hyperparameter Tuning

In [89]:
from sklearn.model_selection import GridSearchCV

In [90]:
param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__max_samples':[0.1, 0.25, 0.5, 1.0],
    'regressor__max_features': [1.0, 'sqrt']
}

In [91]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1', OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore'), ['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [92]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor())
])

In [93]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

In [96]:
search = GridSearchCV(pipeline, param_grid, cv=kfold, scoring='r2', n_jobs=1, verbose=4)

In [99]:
search.fit(X, y_transformed)

Fitting 10 folds for each of 128 candidates, totalling 1280 fits
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.884 total time=   0.5s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.908 total time=   0.3s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.895 total time=   0.3s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.885 total time=   0.4s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.879 total time=   0.7s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.863 total time=   0.4s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.872 total time=   0.4s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.875 total time=   0.4s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.843 total time=   0.4s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.869 total time=   0.4s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.889 total time=   0.8s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.909 total time=   1.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.901 total time=   0.7s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.884 total time=   0.7s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.880 total time=   0.7s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.865 total time=   1.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.879 total time=   0.7s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.877 total time=   0.7s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.850 total time=   0.8s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=100;, score=0.867 total time=   1.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.890 total time=   1.7s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.912 total time=   1.4s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.898 total time=   1.9s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.887 total time=   1.6s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.881 total time=   1.9s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.867 total time=   1.3s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.882 total time=   1.9s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.881 total time=   1.5s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.850 total time=   1.3s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=200;, score=0.872 total time=   1.6s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.890 total time=   2.8s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.910 total time=   2.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.900 total time=   2.6s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.888 total time=   2.1s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.882 total time=   2.3s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.868 total time=   2.6s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.882 total time=   2.1s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.879 total time=   2.5s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.855 total time=   2.5s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.1, regressor__n_estimators=300;, score=0.873 total time=   2.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.898 total time=   0.7s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.920 total time=   1.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.916 total time=   0.6s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.900 total time=   0.6s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.897 total time=   0.6s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.876 total time=   1.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.888 total time=   0.6s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.886 total time=   0.6s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.870 total time=   0.7s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.882 total time=   0.7s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.897 total time=   1.7s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.922 total time=   1.3s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.919 total time=   1.7s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.901 total time=   1.4s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.896 total time=   1.2s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.878 total time=   1.6s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.891 total time=   1.2s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.889 total time=   1.6s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.861 total time=   1.4s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.884 total time=   1.2s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.896 total time=   2.9s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.923 total time=   2.9s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.917 total time=   2.9s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.901 total time=   2.8s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.899 total time=   2.6s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.878 total time=   2.9s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.891 total time=   3.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.889 total time=   2.5s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.865 total time=   2.8s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=200;, score=0.887 total time=   2.7s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.896 total time=   4.3s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.924 total time=   4.2s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.917 total time=   4.4s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.901 total time=   3.5s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.900 total time=   4.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.882 total time=   3.4s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.890 total time=   3.8s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.889 total time=   3.7s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.862 total time=   4.4s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.25, regressor__n_estimators=300;, score=0.884 total time=   4.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.903 total time=   1.5s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.925 total time=   1.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.925 total time=   1.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.904 total time=   1.4s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.908 total time=   1.2s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.888 total time=   1.1s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.891 total time=   1.4s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.893 total time=   1.1s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.869 total time=   0.9s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.888 total time=   0.9s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.900 total time=   1.8s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.930 total time=   1.8s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.922 total time=   2.2s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.904 total time=   2.1s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.907 total time=   1.8s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.885 total time=   2.5s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.895 total time=   2.4s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.894 total time=   2.2s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.872 total time=   2.5s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.893 total time=   2.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.900 total time=   4.5s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.932 total time=   4.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.923 total time=   3.8s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.906 total time=   4.7s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.909 total time=   4.4s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.885 total time=   4.2s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.894 total time=   4.7s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.894 total time=   4.5s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.867 total time=   4.6s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=200;, score=0.892 total time=   4.6s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.904 total time=   6.4s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.932 total time=   7.2s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.925 total time=   7.2s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.906 total time=   6.9s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.909 total time=   6.6s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.884 total time=   6.9s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.895 total time=   6.9s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.894 total time=   6.1s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.867 total time=   6.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=0.5, regressor__n_estimators=300;, score=0.892 total time=   6.3s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.900 total time=   1.6s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.935 total time=   1.8s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.920 total time=   1.5s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.902 total time=   1.5s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=1.0, regressor__max_samples=1.0, regressor__n_estimators=50;, score=0.909 total time=   1.4s

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['bedRoom',
                                                                          'bathroom',
                                                                          'built_up_area',
                                                                          'servant '
                                                                          'room',
                                                                          'store '
                                                                          'room']),
                                                                        ('cat',
                                                                         OrdinalEncoder(),
                                                                         ['property_type',
                                                                          'sector',
                                                                          'balcony',
                                                                          'agePossession',
                                                                          'furnishing_type',...
                                                                                       handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         ['agePossession']),
                                                                        ('target_enc',
                                                                         TargetEncoder(),
                                                                         ['sector'])])),
                                       ('regressor', RandomForestRegressor())]),
             n_jobs=1,
             param_grid={'regressor__max_depth': [None, 10, 20, 30],
                         'regressor__max_features': [1.0, 'sqrt'],
                         'regressor__max_samples': [0.1, 0.25, 0.5, 1.0],
                         'regressor__n_estimators': [50, 100, 200, 300]},
             scoring='r2', verbose=4)

In [100]:
final_pipe = search.best_estimator_

In [101]:
search.best_params_

{'regressor__max_depth': 30,
 'regressor__max_features': 'sqrt',
 'regressor__max_samples': 1.0,
 'regressor__n_estimators': 300}

In [102]:
search.best_score_

np.float64(0.9026805619188393)

In [103]:
final_pipe.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['agePossession']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor',
                 RandomForestRegressor(max_depth=30, max_features='sqrt',
                                       max_samples=1.0, n_estimators=300))])

### Exporting the model

In [104]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ], 
    remainder='passthrough'
)

In [105]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=500))
])

In [106]:
pipeline.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['sector',
                                                   'agePossession'])])),
                ('regressor', RandomForestRegressor(n_estimators=500))])

In [107]:
import pickle

with open('pipeline.pkl', 'wb') as file:
    pickle.dump(pipeline, file)

In [108]:
with open('df.pkl', 'wb') as file:
    pickle.dump(X, file)

In [109]:
X

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
3549,flat,sector 84,2.0,2.0,1,Relatively New,532.0,0.0,0.0,unfurnished,Medium,Mid Floor
3550,house,sector 109,5.0,5.0,3+,Relatively New,6228.0,1.0,1.0,unfurnished,High,Low Floor
3551,flat,sector 2,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,semifurnished,Medium,Mid Floor
3552,house,sector 43,5.0,6.0,3,Moderately Old,5490.0,1.0,1.0,unfurnished,Medium,Mid Floor
3553,flat,sector 68,3.0,3.0,3+,Relatively New,1845.0,0.0,0.0,semifurnished,Medium,High Floor

### trying out predictions

In [ ]:
x.columns

In [ ]:
X.iloc[0].values

In [ ]:
data = [['house', 'sector 102', 4, 3, '3+', 'New Property', 2750, 0, 0, 'unfurnished', 'Low', 'Low Floor']]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category']

# Convert to DataFrame
one_df = pd.DataFrame(data, columns=columns)

one_df

In [ ]:
np.expm1(pipeline.predict(one_df))

In [ ]:
X.dtypes

In [ ]:
sorted(X['sector'].unique().tolist())